---
extends: default

rules:
  line-length:
    max: 120  # Increase line length limit from 80 to 120
  document-start:
    present: false  # Don't require document start marker
  trailing-spaces: enable
  indentation:
    spaces: 2
    indent-sequences: true
  hyphens:
    max-spaces-after: 1