# Gemfile for monitoring DevOps tools via Dependabot
# This is a monitoring file - not for actual installation

source 'https://rubygems.org'

ruby '3.0.0'

# gh - https://github.com/cli/cli
gem 'github_cli', '2.78.0'

# kubectl - https://github.com/kubernetes/kubernetes
gem 'kubectl-rb', '1.25.4'

