# Gemfile for monitoring DevOps tools via Dependabot
# This is a monitoring file - not for actual installation

source 'https://rubygems.org'

ruby '3.0.0'

# httpie - https://github.com/httpie/httpie
gem 'httpie', '3.2.4'

# jq - https://github.com/jqlang/jq
gem 'jq', '1.8.1'

# httpie - https://github.com/httpie/httpie
gem 'httpie', '3.2.4'

# jq - https://github.com/jqlang/jq
gem 'jq', '1.8.1'

# httpie - https://github.com/httpie/httpie
gem 'httpie', '3.2.4'

# jq - https://github.com/jqlang/jq
gem 'jq', '1.8.1'

# httpie - https://github.com/httpie/httpie
gem 'httpie', '3.2.4'

# jq - https://github.com/jqlang/jq
gem 'jq', '1.8.1'

# node - https://github.com/nodejs/node
gem 'node', '24.6.0'

# ollama - https://github.com/ollama/ollama
gem 'ollama', '0.11.4'

# code - https://github.com/microsoft/vscode
gem 'code', '1.103.2'

# ollama - https://github.com/ollama/ollama
gem 'ollama', '0.11.4'

# httpie - https://github.com/httpie/httpie
gem 'httpie', '3.2.4'

# jq - https://github.com/jqlang/jq
gem 'jq', '1.8.1'

