# Gemfile for monitoring DevOps tools via Dependabot
# This is a monitoring file - not for actual installation

source 'https://rubygems.org'

ruby '3.0.0'

# Common Ruby gems for development tools monitoring
gem 'rake', '13.0.6'
gem 'bundler', '2.4.10' 
gem 'rspec', '3.12.0'
gem 'rubocop', '1.56.0'
gem 'yard', '0.9.34'
gem 'puma', '6.3.1'

