name: Auto Update Tools
# 日次実行でDependabot対象外ツールの更新をチェックし、PR自動作成

on:
  schedule:
    # 毎日9:00 UTC (JST 18:00) に実行
    - cron: '0 9 * * *'
  
  # 手動実行も可能
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
    check-updates:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v5

        - name: Set up environment
          run: |
            # 必要なツールが使用可能か確認
            echo "GitHub CLI version: $(gh --version)"
            echo "curl version: $(curl --version | head -1)"
            echo "jq version: $(jq --version)"

        - name: Check for tool updates
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            echo "=== 自動更新チェック開始 ==="

            # バージョンチェッカースクリプト実行
            if [[ -f "./version-checker.sh" ]]; then
              bash ./version-checker.sh --check-all --output-format=json > update-results.json
            else
              echo "version-checker.sh が見つかりません"
              exit 1
            fi

            # 結果確認
            if [[ -s update-results.json ]]; then
              echo "更新が必要なツールを検出しました："
              cat update-results.json
            else
              echo "すべてのツールが最新版です"
              exit 0
            fi

        - name: Create pull requests for updates
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            if [[ -f "update-results.json" && -s "update-results.json" ]]; then
              echo "=== PR作成処理開始 ==="

              # PR作成スクリプト実行
              if [[ -f "./pr-creator.sh" ]]; then
                bash ./pr-creator.sh --input-file=update-results.json
              else
                echo "pr-creator.sh が見つかりません"
                exit 1
              fi
            else
              echo "更新対象なし - PR作成をスキップ"
            fi

        - name: Cleanup
          if: always()
          run: |
            # 一時ファイルをクリーンアップ
            rm -f update-results.json
            echo "=== 自動更新チェック完了 ==="